# LuckyDropper Configuration

# Game Settings
settings:
  min_players: 2
  max_players: 8
  start_countdown: 30
  game_duration: 300 # 5 minutes
  allow_spectators: true
  auto_start: true
  auto_join: true

# Schema Settings
schema:
  lobby_schematic: "lobby"
  map_schematic_folder: "maps"
  auto_load: true
  spacing: 16 # Minimum space between schematics
  check_area: true # Check if area is occupied before placing schematic

# Voting Settings
vote:
  duration: 30 # Seconds
  min_votes: 1
  items:
    voting:
      material: "PAPER"
      name: "&aVote for Map"
      lore:
        - "&7Click to vote for a map!"
        - "&7Current votes: &e{votes}"
    leave:
      material: "BARRIER"
      name: "&cLeave Game"
      lore:
        - "&7Click to leave the game"
    map_item:
      material: "MAP"
      name_format: "&b{map_name}"
      lore:
        - "&7Votes: &e{votes}"
        - "&7Click to vote!"

# Reward Settings
rewards:
  first:
    commands:
      - "give %player% diamond 1"
      - "eco give %player% 100"
  second:
    commands:
      - "give %player% gold_ingot 1"
      - "eco give %player% 50"
  third:
    commands:
      - "give %player% iron_ingot 1"
      - "eco give %player% 25"
  participation:
    commands:
      - "eco give %player% 10"

# Message Settings
messages:
  prefix: "&8[&bLuckyDropper&8] "
  join: "&a%player% has joined the game! (%current%/%max%)"
  leave: "&c%player% has left the game! (%current%/%max%)"
  start: "&aGame has started!"
  end: "&cGame has ended!"
  win: "&a%player% has won the game!"
  checkpoint: "&aCheckpoint set!"
  death: "&c%player% died! Deaths: %deaths%"

# Database Settings (for future use)
database:
  enabled: false
  type: "sqlite" # sqlite or mysql
  mysql:
    host: "localhost"
    port: 3306
    database: "luckydropper"
    username: "root"
    password: "password"

# Debug Settings
debug:
  enabled: false
  log_level: "INFO" # INFO, WARNING, ERROR
  show_debug_messages: false
