name: LuckyDropper
version: '${project.version}'
main: me.kinawn.lnplugins.luckydropper.LuckyDropper
api-version: '1.8'
authors: [kinawn]
description: A dropper minigame plugin with modern features
depend: [WorldEdit]

commands:
  dropper:
    description: Main command for the LuckyDropper plugin
    usage: /<command> [join|leave|vote|stats]
    aliases: [ld, luckydropper]
  dropperadmin:
    description: Admin commands for the LuckyDropper plugin
    usage: /<command> [create|delete|setspawn|reload]
    aliases: [ldadmin, luckydropperadmin]
    permission: luckydropper.admin

permissions:
  luckydropper.*:
    description: Gives access to all LuckyDropper commands
    children:
      luckydropper.admin: true
      luckydropper.play: true
  luckydropper.admin:
    description: Gives access to admin commands
    default: op
  luckydropper.play:
    description: Allows players to play the game
    default: true
  luckydropper.vote:
    description: Allows players to vote for maps
    default: true
  luckydropper.stats:
    description: Allows players to view their stats
    default: true